### PR TITLE
Feat  basic views

### PR DESCRIPTION
**Pull request by dafrie**
This PR adds #2.

TODO:
- The createChapter mutation is not yet working

### CODE REVIEW

**Comment by YanickSchraner** [comment]
Works, but maybe we should add input validation to restrict length and numbers (float?)
Also I am not sure if that kind of input for chapter number will work, but we can keep it for the moment.
I am not sure if we should make the UI in German. If our translators want to use that UI they need to understand German and thats not given. Maybe we should switch to English?

**Comment by dafrie** [comment]
regarding languages: Good point, I was actually unsure which language to use... I now added react-i18next (but only for chapters now, will have to refactor the rest in a other PR) which allows the user to set his language in the settings page

**Comment by dafrie** [comment]
Regarding input validation/fields: The chapter number field is anyway not available on the backend, but when I was doing the input form, I noticed that we actually would need such kind of field (for ordering for example). Input validation: I added some restrictions to the fields. The other input validation can come server-side from Graphene or we add a proper "form" library that handles this for us... Since we shouldn't have too many other fforms, I was unsure wether we need this additional burden...

**Comment by YanickSchraner** [comment]
> 
> 
> Regarding input validation/fields: The chapter number field is anyway not available on the backend, but when I was doing the input form, I noticed that we actually would need such kind of field (for ordering for example). Input validation: I added some restrictions to the fields. The other input validation can come server-side from Graphene or we add a proper "form" library that handles this for us... Since we shouldn't have too many other fforms, I was unsure wether we need this additional burden...

I also thought about those missing fields. I think we have to discuss this shortly and then open an issue on backend repo and adjust the db model :-)

Regarding forms: Maybe we should just add such a library, we never know how much further forms will come and I think its always good if we detect such things already in the frontend. Offcouse the backend will check this again.

**Comment by YanickSchraner** [comment]
> 
> 
> This PR adds #2.
> 
> TODO:
> 
>     * The createChapter mutation is not yet working

is that still an issue?

**Comment by dafrie** [comment]
> > Regarding input validation/fields: The chapter number field is anyway not available on the backend, but when I was doing the input form, I noticed that we actually would need such kind of field (for ordering for example). Input validation: I added some restrictions to the fields. The other input validation can come server-side from Graphene or we add a proper "form" library that handles this for us... Since we shouldn't have too many other fforms, I was unsure wether we need this additional burden...
> 
> I also thought about those missing fields. I think we have to discuss this shortly and then open an issue on backend repo and adjust the db model :-)

Sure - lets do this. Are you available tomorrow or this weekend?
> 
> Regarding forms: Maybe we should just add such a library, we never know how much further forms will come and I think its always good if we detect such things already in the frontend. Offcouse the backend will check this again.

Ok - I will do some investigation. Since I am lazy and the forms would most probably already be typed through the GraphQL schema, something like https://github.com/mozilla-services/react-jsonschema-form would be nice :)

**Comment by dafrie** [comment]
> > This PR adds #2.
> > TODO:
> > ```
> > * The createChapter mutation is not yet working
> > ```
> 
> is that still an issue?

I think so, but once the Auth/JWT issue is resolved, it should work

**Comment by YanickSchraner** [comment]
> 
> 
> > > Regarding input validation/fields: The chapter number field is anyway not available on the backend, but when I was doing the input form, I noticed that we actually would need such kind of field (for ordering for example). Input validation: I added some restrictions to the fields. The other input validation can come server-side from Graphene or we add a proper "form" library that handles this for us... Since we shouldn't have too many other fforms, I was unsure wether we need this additional burden...
> > 
> > 
> > I also thought about those missing fields. I think we have to discuss this shortly and then open an issue on backend repo and adjust the db model :-)
> 
> Sure - lets do this. Are you available tomorrow or this weekend?
> 
> > Regarding forms: Maybe we should just add such a library, we never know how much further forms will come and I think its always good if we detect such things already in the frontend. Offcouse the backend will check this again.
> 
> Ok - I will do some investigation. Since I am lazy and the forms would most probably already be typed through the GraphQL schema, something like https://github.com/mozilla-services/react-jsonschema-form would be nice :)

As I don't have much experience with react I will trust your decision :-) react-json looks good, can we connect the schema right away with the GraphQL schema? That would be cool. One concern: Our forms are currently from material and not bootstrap right? I would like to stick with just one of them or do I confuse something?

**Comment by dafrie** [comment]
Sorry, I screwed up with the branches here and created a "duplicate" (PR #26)  which is based on the other feature branch #25. So I think we have to close this one...

**Pull request closed without merging**
